# application.yml
server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: post-api
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    exchange: ${RABBITMQ_EXCHANGE:notificationExchange}
    routingkey: ${RABBITMQ_ROUTING_KEY:notificationKey}
    queue: ${RABBITMQ_QUEUE:notificationQueue}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:drinkwithme}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

upload:
  dir: uploads/

external-link:
  #url: "https://socialize-fe.netlify.app/images/"
  url: "http://localhost:8081/images/"

image:
  service:
    url: ${IMAGE_API_URL:http://localhost:8085}